-- RLM and analytics extension schema. Run after base ingest schema.
-- Requires: Postgres with base tables (runs, events, state_snapshots, completed_trades).

-- Hypotheses: generated by RLM, testable market claims
CREATE TABLE IF NOT EXISTS hypotheses (
    id BIGSERIAL PRIMARY KEY,
    hypothesis_id TEXT NOT NULL UNIQUE,
    generation INT NOT NULL DEFAULT 1,
    parent_hypothesis_id TEXT,
    claim_text TEXT NOT NULL,
    regime_context TEXT,
    status TEXT NOT NULL CHECK (status IN ('pending', 'testing', 'supported', 'rejected')),
    independent_var TEXT,
    dependent_vars JSONB,
    control_vars JSONB,
    test_window JSONB,
    mutation_directive TEXT,
    mutation_type TEXT CHECK (mutation_type IN ('refine', 'expand', 'pivot')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_hypotheses_status ON hypotheses(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_hypotheses_generation ON hypotheses(generation);
CREATE INDEX IF NOT EXISTS idx_hypotheses_parent ON hypotheses(parent_hypothesis_id) WHERE parent_hypothesis_id IS NOT NULL;

-- Experiment configs: test definitions for a hypothesis
CREATE TABLE IF NOT EXISTS experiment_configs (
    id BIGSERIAL PRIMARY KEY,
    hypothesis_id TEXT NOT NULL REFERENCES hypotheses(hypothesis_id) ON DELETE CASCADE,
    config_json JSONB NOT NULL,
    entry_rules JSONB,
    exit_rules JSONB,
    position_sizing JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_experiment_configs_hypothesis ON experiment_configs(hypothesis_id);

-- Experiment results: outcomes of running an experiment
CREATE TABLE IF NOT EXISTS experiment_results (
    id BIGSERIAL PRIMARY KEY,
    hypothesis_id TEXT NOT NULL REFERENCES hypotheses(hypothesis_id) ON DELETE CASCADE,
    config_id BIGINT REFERENCES experiment_configs(id) ON DELETE SET NULL,
    run_id TEXT,
    sharpe REAL,
    win_rate REAL,
    max_drawdown REAL,
    edge_per_trade REAL,
    oos_is_decay_ratio REAL,
    regime_segmentation JSONB,
    temporal_thirds JSONB,
    p_value REAL,
    bh_fdr_adjusted REAL,
    verdict TEXT NOT NULL CHECK (verdict IN ('supported', 'rejected', 'inconclusive')),
    confidence_score REAL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_experiment_results_hypothesis ON experiment_results(hypothesis_id);
CREATE INDEX IF NOT EXISTS idx_experiment_results_verdict ON experiment_results(verdict, created_at DESC);

-- Knowledge store: persisted conclusions for recursive context
CREATE TABLE IF NOT EXISTS knowledge_store (
    id BIGSERIAL PRIMARY KEY,
    hypothesis_id TEXT NOT NULL REFERENCES hypotheses(hypothesis_id) ON DELETE CASCADE,
    result_id BIGINT REFERENCES experiment_results(id) ON DELETE SET NULL,
    verdict TEXT NOT NULL,
    confidence_score REAL,
    mutation_directive TEXT,
    regime_tags JSONB,
    survival_count INT DEFAULT 0,
    rejection_count INT DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_validated_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_knowledge_store_hypothesis ON knowledge_store(hypothesis_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_store_created ON knowledge_store(created_at DESC);

-- Trade embeddings: vector representation for semantic search (DOUBLE PRECISION[] for portability; pgvector optional later)
CREATE TABLE IF NOT EXISTS trade_embeddings (
    id BIGSERIAL PRIMARY KEY,
    trade_id BIGINT NOT NULL REFERENCES completed_trades(id) ON DELETE CASCADE,
    embedding DOUBLE PRECISION[] NOT NULL,
    embedding_model TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(trade_id)
);

CREATE INDEX IF NOT EXISTS idx_trade_embeddings_trade_id ON trade_embeddings(trade_id);

-- Runtime logs shipped from the local trader so operators can inspect failures remotely without a cloud->Mac control path.
CREATE TABLE IF NOT EXISTS runtime_logs (
    id BIGSERIAL PRIMARY KEY,
    run_id TEXT,
    logged_at TIMESTAMPTZ NOT NULL,
    inserted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    level TEXT,
    logger_name TEXT,
    source TEXT,
    service_name TEXT,
    process_id INT,
    line_hash TEXT,
    message TEXT NOT NULL,
    payload_json JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_runtime_logs_run_id ON runtime_logs(run_id, logged_at DESC);
CREATE INDEX IF NOT EXISTS idx_runtime_logs_logged_at ON runtime_logs(logged_at DESC);
CREATE INDEX IF NOT EXISTS idx_runtime_logs_level ON runtime_logs(level, logged_at DESC);

-- Internal memory graph: nodes (hypotheses, conclusions, trade clusters, regime snapshots)
CREATE TABLE IF NOT EXISTS memory_nodes (
    id BIGSERIAL PRIMARY KEY,
    node_id TEXT NOT NULL UNIQUE,
    node_type TEXT NOT NULL CHECK (node_type IN ('hypothesis', 'conclusion', 'trade_cluster', 'regime_snapshot')),
    payload_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_memory_nodes_type ON memory_nodes(node_type);

-- Internal memory graph: edges (supports, rejects, similar_to, precedes)
CREATE TABLE IF NOT EXISTS memory_edges (
    id BIGSERIAL PRIMARY KEY,
    from_node_id TEXT NOT NULL REFERENCES memory_nodes(node_id) ON DELETE CASCADE,
    to_node_id TEXT NOT NULL REFERENCES memory_nodes(node_id) ON DELETE CASCADE,
    edge_type TEXT NOT NULL CHECK (edge_type IN ('supports', 'rejects', 'similar_to', 'precedes')),
    payload_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(from_node_id, to_node_id, edge_type)
);

CREATE INDEX IF NOT EXISTS idx_memory_edges_from ON memory_edges(from_node_id);
CREATE INDEX IF NOT EXISTS idx_memory_edges_to ON memory_edges(to_node_id);
CREATE INDEX IF NOT EXISTS idx_memory_edges_type ON memory_edges(edge_type);

-- Replay metadata: runs that have been replayed (no live broker API)
CREATE TABLE IF NOT EXISTS replay_runs (
    id BIGSERIAL PRIMARY KEY,
    run_id TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'running', 'completed', 'failed')),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    result_summary JSONB,
    what_if_config JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_replay_runs_run_id ON replay_runs(run_id);
CREATE INDEX IF NOT EXISTS idx_replay_runs_status ON replay_runs(status);

-- AI reports: persisted on-demand report bundles for the web dashboard
CREATE TABLE IF NOT EXISTS ai_reports (
    id BIGSERIAL PRIMARY KEY,
    report_id TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    report_type TEXT NOT NULL DEFAULT 'on_demand',
    model_provider TEXT NOT NULL,
    model_name TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'completed', 'failed')),
    summary_text TEXT NOT NULL,
    report_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_ai_reports_created_at ON ai_reports(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_reports_report_id ON ai_reports(report_id);

-- Read models for dashboard and remote investigation.
CREATE MATERIALIZED VIEW IF NOT EXISTS mv_run_summaries AS
WITH event_agg AS (
    SELECT
        run_id,
        COUNT(*) AS event_count,
        MAX(event_timestamp) AS latest_event_at,
        MAX(CASE WHEN event_type IN ('trade_blocked', 'risk_state_changed', 'fail_safe_activated', 'duplicate_unresolved_entry_detected', 'unresolved_entry_tracked', 'unresolved_entry_cleared') THEN event_timestamp END) AS latest_blocker_at
    FROM events
    GROUP BY run_id
),
state_agg AS (
    SELECT
        run_id,
        COUNT(*) AS state_snapshot_count,
        MAX(captured_at) AS latest_state_at
    FROM state_snapshots
    GROUP BY run_id
),
decision_agg AS (
    SELECT
        run_id,
        COUNT(*) AS decision_snapshot_count,
        MAX(decided_at) AS latest_decision_at
    FROM decision_snapshots
    GROUP BY run_id
),
market_agg AS (
    SELECT
        run_id,
        COUNT(*) AS market_tape_count,
        MAX(captured_at) AS latest_market_at
    FROM market_tape
    GROUP BY run_id
),
order_agg AS (
    SELECT
        run_id,
        COUNT(*) AS order_lifecycle_count,
        MAX(observed_at) AS latest_order_at
    FROM order_lifecycle
    GROUP BY run_id
),
trade_agg AS (
    SELECT
        run_id,
        COUNT(*) AS trade_count,
        COALESCE(SUM(pnl), 0) AS total_pnl,
        MAX(COALESCE(exit_time, inserted_at)) AS latest_trade_at
    FROM completed_trades
    GROUP BY run_id
),
runtime_log_agg AS (
    SELECT
        run_id,
        COUNT(*) AS runtime_log_count,
        MAX(logged_at) AS latest_runtime_log_at
    FROM runtime_logs
    GROUP BY run_id
)
SELECT
    r.run_id,
    r.created_at,
    r.last_seen_at,
    r.process_id,
    r.data_mode,
    r.symbol,
    r.account_id,
    r.account_name,
    r.account_mode,
    r.account_is_practice,
    r.status,
    r.zone,
    r.zone_state,
    r.position,
    r.position_pnl,
    r.daily_pnl,
    r.risk_state,
    COALESCE(e.event_count, 0) AS event_count,
    COALESCE(s.state_snapshot_count, 0) AS state_snapshot_count,
    COALESCE(d.decision_snapshot_count, 0) AS decision_snapshot_count,
    COALESCE(m.market_tape_count, 0) AS market_tape_count,
    COALESCE(o.order_lifecycle_count, 0) AS order_lifecycle_count,
    COALESCE(t.trade_count, 0) AS trade_count,
    COALESCE(l.runtime_log_count, 0) AS runtime_log_count,
    COALESCE(t.total_pnl, 0) AS total_pnl,
    s.latest_state_at,
    d.latest_decision_at,
    m.latest_market_at,
    o.latest_order_at,
    l.latest_runtime_log_at,
    e.latest_event_at,
    t.latest_trade_at,
    e.latest_blocker_at
FROM runs r
LEFT JOIN event_agg e ON e.run_id = r.run_id
LEFT JOIN state_agg s ON s.run_id = r.run_id
LEFT JOIN decision_agg d ON d.run_id = r.run_id
LEFT JOIN market_agg m ON m.run_id = r.run_id
LEFT JOIN order_agg o ON o.run_id = r.run_id
LEFT JOIN runtime_log_agg l ON l.run_id = r.run_id
LEFT JOIN trade_agg t ON t.run_id = r.run_id;

CREATE UNIQUE INDEX IF NOT EXISTS idx_mv_run_summaries_run_id ON mv_run_summaries(run_id);
CREATE INDEX IF NOT EXISTS idx_mv_run_summaries_latest_seen ON mv_run_summaries(COALESCE(last_seen_at, created_at) DESC);

CREATE MATERIALIZED VIEW IF NOT EXISTS mv_daily_trade_stats AS
SELECT
    DATE(COALESCE(exit_time, inserted_at)) AS trade_day,
    COUNT(*) AS trade_count,
    COALESCE(SUM(pnl), 0) AS total_pnl,
    COALESCE(AVG(pnl), 0) AS avg_pnl,
    COALESCE(MAX(pnl), 0) AS best_trade,
    COALESCE(MIN(pnl), 0) AS worst_trade
FROM completed_trades
GROUP BY DATE(COALESCE(exit_time, inserted_at));

CREATE UNIQUE INDEX IF NOT EXISTS idx_mv_daily_trade_stats_day ON mv_daily_trade_stats(trade_day);

CREATE OR REPLACE VIEW v_run_timeline AS
SELECT
    run_id,
    event_timestamp AS timeline_at,
    'event' AS kind,
    category,
    event_type,
    source,
    symbol,
    zone,
    action,
    reason,
    order_id,
    risk_state,
    payload_json
FROM events
UNION ALL
SELECT
    run_id,
    captured_at AS timeline_at,
    'state_snapshot' AS kind,
    status AS category,
    data_mode AS event_type,
    NULL::text AS source,
    symbol,
    zone,
    zone_state AS action,
    last_entry_block_reason AS reason,
    NULL::text AS order_id,
    risk_state,
    payload_json
FROM state_snapshots
UNION ALL
SELECT
    run_id,
    decided_at AS timeline_at,
    'decision_snapshot' AS kind,
    action AS category,
    reason AS event_type,
    decision_id AS source,
    symbol,
    zone,
    outcome AS action,
    outcome_reason AS reason,
    NULL::text AS order_id,
    NULL::text AS risk_state,
    payload_json
FROM decision_snapshots
UNION ALL
SELECT
    run_id,
    observed_at AS timeline_at,
    'order_lifecycle' AS kind,
    event_type AS category,
    status AS event_type,
    order_id AS source,
    symbol,
    zone,
    status AS action,
    reason,
    order_id,
    NULL::text AS risk_state,
    payload_json
FROM order_lifecycle
UNION ALL
SELECT
    run_id,
    captured_at AS timeline_at,
    'market_tape' AS kind,
    symbol AS category,
    trade_side AS event_type,
    source,
    symbol,
    NULL::text AS zone,
    trade_side AS action,
    NULL::text AS reason,
    NULL::text AS order_id,
    NULL::text AS risk_state,
    payload_json
FROM market_tape
UNION ALL
SELECT
    run_id,
    logged_at AS timeline_at,
    'runtime_log' AS kind,
    COALESCE(service_name, logger_name, source) AS category,
    level AS event_type,
    COALESCE(logger_name, source) AS source,
    NULL::text AS symbol,
    NULL::text AS zone,
    level AS action,
    message AS reason,
    NULL::text AS order_id,
    NULL::text AS risk_state,
    payload_json
FROM runtime_logs
UNION ALL
SELECT
    run_id,
    COALESCE(exit_time, inserted_at) AS timeline_at,
    'trade' AS kind,
    strategy AS category,
    regime AS event_type,
    source,
    NULL::text AS symbol,
    zone,
    NULL::text AS action,
    NULL::text AS reason,
    NULL::text AS order_id,
    NULL::text AS risk_state,
    payload_json
FROM completed_trades;
