-- RLM and analytics extension schema. Run after base ingest schema.
-- Requires: Postgres with base tables (runs, events, state_snapshots, completed_trades).

-- Hypotheses: generated by RLM, testable market claims
CREATE TABLE IF NOT EXISTS hypotheses (
    id BIGSERIAL PRIMARY KEY,
    hypothesis_id TEXT NOT NULL UNIQUE,
    generation INT NOT NULL DEFAULT 1,
    parent_hypothesis_id TEXT,
    claim_text TEXT NOT NULL,
    regime_context TEXT,
    status TEXT NOT NULL CHECK (status IN ('pending', 'testing', 'supported', 'rejected')),
    independent_var TEXT,
    dependent_vars JSONB,
    control_vars JSONB,
    test_window JSONB,
    mutation_directive TEXT,
    mutation_type TEXT CHECK (mutation_type IN ('refine', 'expand', 'pivot')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_hypotheses_status ON hypotheses(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_hypotheses_generation ON hypotheses(generation);
CREATE INDEX IF NOT EXISTS idx_hypotheses_parent ON hypotheses(parent_hypothesis_id) WHERE parent_hypothesis_id IS NOT NULL;

-- Experiment configs: test definitions for a hypothesis
CREATE TABLE IF NOT EXISTS experiment_configs (
    id BIGSERIAL PRIMARY KEY,
    hypothesis_id TEXT NOT NULL REFERENCES hypotheses(hypothesis_id) ON DELETE CASCADE,
    config_json JSONB NOT NULL,
    entry_rules JSONB,
    exit_rules JSONB,
    position_sizing JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_experiment_configs_hypothesis ON experiment_configs(hypothesis_id);

-- Experiment results: outcomes of running an experiment
CREATE TABLE IF NOT EXISTS experiment_results (
    id BIGSERIAL PRIMARY KEY,
    hypothesis_id TEXT NOT NULL REFERENCES hypotheses(hypothesis_id) ON DELETE CASCADE,
    config_id BIGINT REFERENCES experiment_configs(id) ON DELETE SET NULL,
    run_id TEXT,
    sharpe REAL,
    win_rate REAL,
    max_drawdown REAL,
    edge_per_trade REAL,
    oos_is_decay_ratio REAL,
    regime_segmentation JSONB,
    temporal_thirds JSONB,
    p_value REAL,
    bh_fdr_adjusted REAL,
    verdict TEXT NOT NULL CHECK (verdict IN ('supported', 'rejected', 'inconclusive')),
    confidence_score REAL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_experiment_results_hypothesis ON experiment_results(hypothesis_id);
CREATE INDEX IF NOT EXISTS idx_experiment_results_verdict ON experiment_results(verdict, created_at DESC);

-- Knowledge store: persisted conclusions for recursive context
CREATE TABLE IF NOT EXISTS knowledge_store (
    id BIGSERIAL PRIMARY KEY,
    hypothesis_id TEXT NOT NULL REFERENCES hypotheses(hypothesis_id) ON DELETE CASCADE,
    result_id BIGINT REFERENCES experiment_results(id) ON DELETE SET NULL,
    verdict TEXT NOT NULL,
    confidence_score REAL,
    mutation_directive TEXT,
    regime_tags JSONB,
    survival_count INT DEFAULT 0,
    rejection_count INT DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_validated_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_knowledge_store_hypothesis ON knowledge_store(hypothesis_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_store_created ON knowledge_store(created_at DESC);

-- Trade embeddings: vector representation for semantic search (DOUBLE PRECISION[] for portability; pgvector optional later)
CREATE TABLE IF NOT EXISTS trade_embeddings (
    id BIGSERIAL PRIMARY KEY,
    trade_id BIGINT NOT NULL REFERENCES completed_trades(id) ON DELETE CASCADE,
    embedding DOUBLE PRECISION[] NOT NULL,
    embedding_model TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(trade_id)
);

CREATE INDEX IF NOT EXISTS idx_trade_embeddings_trade_id ON trade_embeddings(trade_id);

-- Internal memory graph: nodes (hypotheses, conclusions, trade clusters, regime snapshots)
CREATE TABLE IF NOT EXISTS memory_nodes (
    id BIGSERIAL PRIMARY KEY,
    node_id TEXT NOT NULL UNIQUE,
    node_type TEXT NOT NULL CHECK (node_type IN ('hypothesis', 'conclusion', 'trade_cluster', 'regime_snapshot')),
    payload_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_memory_nodes_type ON memory_nodes(node_type);

-- Internal memory graph: edges (supports, rejects, similar_to, precedes)
CREATE TABLE IF NOT EXISTS memory_edges (
    id BIGSERIAL PRIMARY KEY,
    from_node_id TEXT NOT NULL REFERENCES memory_nodes(node_id) ON DELETE CASCADE,
    to_node_id TEXT NOT NULL REFERENCES memory_nodes(node_id) ON DELETE CASCADE,
    edge_type TEXT NOT NULL CHECK (edge_type IN ('supports', 'rejects', 'similar_to', 'precedes')),
    payload_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(from_node_id, to_node_id, edge_type)
);

CREATE INDEX IF NOT EXISTS idx_memory_edges_from ON memory_edges(from_node_id);
CREATE INDEX IF NOT EXISTS idx_memory_edges_to ON memory_edges(to_node_id);
CREATE INDEX IF NOT EXISTS idx_memory_edges_type ON memory_edges(edge_type);

-- Replay metadata: runs that have been replayed (no live broker API)
CREATE TABLE IF NOT EXISTS replay_runs (
    id BIGSERIAL PRIMARY KEY,
    run_id TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'running', 'completed', 'failed')),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    result_summary JSONB,
    what_if_config JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_replay_runs_run_id ON replay_runs(run_id);
CREATE INDEX IF NOT EXISTS idx_replay_runs_status ON replay_runs(status);
